### ISSUE TITLE
As Ozzy, I want an awesome monkey logo!

### ISSUE THREAD

**Issue by labofoz** [handsfreejs/logo#1]
## Overview
I really like the idea of using a monkey as our logo for a number of reasons:

- There's an emoji for it 🐵
- Many of my first memories are centered around monkeys (my first fears, my first usernames, my first nicknames, etc)
- We have a common ancestor, so telling a story of us progressing towards the singularity would be cool
- It gives us a mascot logo to have fun with (like GitHubs)

## Inspirations
![image](https://user-images.githubusercontent.com/41490928/44179656-e87b1680-a0ac-11e8-9d73-add8d332f9d6.png)
- https://www.designevo.com/apps/logo/?name=cute-monkey-and-interesting-gaming

## Tasks
- [x] Import the monkey above
- [x] Tweak it so that it has star eyes and the circle mouth they make when they "ooh ooh" (as in "ooh ooh aah aah")
![image](https://user-images.githubusercontent.com/41490928/44179700-38f27400-a0ad-11e8-8445-d93c4f774516.png)
- [x] Create a blank face for future edits

**Comment by labofoz** [comment]
Finished!

![image](https://user-images.githubusercontent.com/41490928/44180485-8cff5780-a0b1-11e8-8693-191bd66935be.png)
