### ISSUE TITLE
As a user, I want a way to easily change the colors

### ISSUE THREAD

**Issue by labofoz** [handsfreejs/logo#2]
## Overview
Let's add [control-panel](https://github.com/freeman-lab/control-panel) in order to easily change the colors

## Tasks
- [x] Install control-panel
- [x] Change fur color
- [x] Change skin color

**Comment by labofoz** [comment]
Finished!
![image](https://user-images.githubusercontent.com/41490928/44181857-0fd7e080-a0b9-11e8-82b2-3a5636064dcb.png)
