### ISSUE TITLE
As a user, I want my colors remembered

### ISSUE THREAD

**Issue by labofoz** [handsfreejs/logo#3]
## Overview
Let's make it so that the colors are persisted. Let's use [lockr](https://github.com/tsironis/lockr) and defer this with [lodash](https://lodash.com/)

## Tasks
- [x] Install lockr and lodash
- [x] Persist the settings into localstorage with lockr
- [x] Throttle persistence with lodash

**Comment by labofoz** [comment]
Finished!
![image](https://user-images.githubusercontent.com/41490928/44182335-680fe200-a0bb-11e8-83dc-6003935b088d.png)
