### ISSUE TITLE
As a user, I want to quickly download PNG's

### ISSUE THREAD

**Issue by labofoz** [handsfreejs/logo#4]
## Overview
Let's add buttons to download the SVG's as PNG's using [canvg](https://github.com/canvg/canvg)

## Tasks
- [x] Install canvg
- [x] On download button click, parse the SVG
- [x] Add a field for setting the PNG size
- [x] Add a field for naming the file

**Comment by labofoz** [comment]
Done!

![ezgif-4-affdf2c0a8](https://user-images.githubusercontent.com/41490928/44190398-740b9c00-a0db-11e8-95c0-50af57eb43c7.gif)
